#!/bin/bash


# HeadsUp: This bash script cannot track changes.
#          You have to compile your project before you run it.

# This bash script is written, tested and maintaied by me(arcatra),
# and you're free to use, add, and update this script as you need.

# How to run this file:
#   NOTE: Update the folder structure for "root", "bin" and "lib" as needed.
#   Navigate to the parent dir of this script, and make it executable: chmod +x ./noter
#   run it: ./noter <any args> (You have to specify the path, if this script is not in PWD)
#   NOTE: This is a one time setup, and you can pass args if needed "noter" will pass them directly to java.

YELLOW="\033[0;93m"
RED="\033[0;31m"
GREEN="\033[0;32m"
NC="\033[0m"

printf "${YELLOW}Noter build script${NC}\n\n"

# echo "Use 12(compile, run), 21(run, compile), for more flexibility"
# printf "1. compile,\n2. run,\n3. exit\n[1/2/3]\n(default: 2)\nChoice? : "
# read -r choice

root="./app/src/main/java/"
bin="./app/bin/main/"
lib="./app/lib/*"

mkdir -p "$bin"
mkdir -p "./app/lib"

compile () {
    printf "${GREEN}Compiling sources..${NC}\n"
    find "$root" -name "*.java" -print0 | xargs -0 javac -cp "$lib" -d "$bin" || exit 1
    printf "Done\n"
}

compile

# run() {
#     echo
#     if [[ -z "$( ls -A "$bin")" ]]; then
#         printf "${RED}bin/ is empty, Project is not compiled yet, Starting compile${NC}\n\n"
#         compile
#
#     fi
#     printf "${GREEN}Using classpath: ${bin}, ${lib}${NC}\n\n"
#
#     java --enable-native-access=ALL-UNNAMED -classpath "${bin}:${lib}" noter.Noter "$@" || exit 1
#     # "--enable-native-access=ALL-UNNAMED" is required for some external libraries like SQLite,
#     # If you're not using any external libraries you can remove this.
#     echo
# }

# case "$choice" in
#     12)
#         compile
#         run "$@"
#     ;;
#     21)
#         run "$@"
#         compile
#     ;;
#     1) 
#         compile
#     ;;
#     2 | "") 
#         run "$@"
#     ;;
#     3) 
#         printf "${GREEN}Halting the process${NC}\n"
#         echo 
#
#         exit
#         ;;
#     *)
#         printf "${RED}Invalid input${NC}\n"
#         ;;
#
# esac
#
#
