#!/bin/bash 


# NOTE: Use this bash script with caution, as this script cannot track changes.
#       You have to compile your project before you run it.

# This bash script is written, tested and maintaied by me(arcatra),
# and you're free to use, add, and update this script as you need.

# How to run this file:
#   NOTE: Update the folder structure for "root", "bin" and "lib" as needed.
#   Navigate to the parent dir of this script, and make it executable: chmod +x ./crun
#   run it: ./crun <any args>
#   NOTE: This is a one time setup, and you can pass args if needed "crun" will pass them directly to java.


echo "Use 12(compile, run), 21(run, compile), for more flexibility"
printf "1. compile,\n2. run,\n3. exit\n[1/2/3]\n(default: 2)\nChoice? : "
read -r choice

root=./app/src/main/java/
bin=./app/bin/main/
lib=./app/lib/*

compile () {
    echo "Compiling sources.."
    find "$root" -name "*.java" -print0 | xargs -0 javac -cp "$lib" -d "$bin" || exit 1
    printf "Done\n"
}

run() {
    echo
    echo "Using classpath: ${bin}, $lib"

    java --enable-native-access=ALL-UNNAMED -classpath "${bin}:${lib}" noter.Noter "$@" || exit 1
    # "--enable-native-access=ALL-UNNAMED" is required for some external libraries like SQLite,
    # If you're not using any external libraries you can remove this.
    echo
}

case "$choice" in
    12)
        compile
        run "$@"
    ;;
    21)
        run "$@"
        compile
    ;;
    1) 
        compile
    ;;
    2 | "") 
        run "$@"
    ;;
    3) 
        echo "Halting the process"
        echo 

        exit
    ;;
    *)
    echo "Invalid input"
    ;;

esac


