#!/bin/bash

# NOTE: This is a gradelw only bash script

buil() {
    ./gradlew build -q

}

runWithArgs() {
    ./gradlew run -q --args="${*@Q}" || exit 1

}

run() {
    ./gradlew run

}

if [[ $# -eq 0 ]]; then
   run
   exit 0

fi

build
runWithArgs "${*@Q}" 

