#!/bin/bash

# NOTE: This is a gradelw only bash script

build() {
    ./gradlew build -q

}

runWithArgs() {
    ./gradlew run -q --args="${*@Q}" || exit 1

}

run() {
    ./gradlew run

}

if [[ $# -eq 0 ]]; then
   run
   echo "No args"
   exit 0

fi

build
runWithArgs "$@" 

