/*
 * This source file was generated by the Gradle 'init' task
 */
package noter;

public class Noter {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Noter().getGreeting());
    }
}
